name: Jenkins Checks
on: [pull_request]

jobs:
  jenkins-check:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Jenkins Build
      id: trigger-jenkins-build
      uses: actions/github-script@v3
      with:
        github-token: ${{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
 }}
        script: |
          const inputs = {
            job: 'statuschecks',
            serverUrl: 'http://52.14.62.107:8080/job/statuschecks/'
          };
          const response = await github.actions.createWorkflowDispatchEvent('jenkins-checks', inputs);
